import {
  Award,
  BadgeCheck,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  Calculator,
  CalendarDays,
  ChartNoAxesColumn,
  ClipboardList,
  CreditCard,
  ExternalLink,
  FileBadge,
  Files,
  FlaskConical,
  GraduationCap,
  Hash,
  HeartHandshake,
  Landmark,
  Languages,
  LibraryBig,
  MapPinned,
  Monitor,
  Presentation,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Trees,
  University,
  UserRound,
} from "lucide-react";

const icons = {
  Award,
  BadgeCheck,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  Calculator,
  CalendarDays,
  ChartNoAxesColumn,
  ClipboardList,
  CreditCard,
  ExternalLink,
  FileBadge,
  Files,
  FlaskConical,
  GraduationCap,
  Hash,
  HeartHandshake,
  Landmark,
  Languages,
  LibraryBig,
  MapPinned,
  Monitor,
  Presentation,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Trees,
  University,
  UserRound,
};

export default function Icon({ name, size = 22, ...props }) {
  const Component = icons[name] || BookOpenText;
  return <Component aria-hidden="true" size={size} {...props} />;
}
